Links act in the same way and use the same colors
fossasia/pslab.fossasia.org pull request #51
Opened 2016-12-27 11:59 UTC by hemanthsavasere

2016-12-27 13:06 UTC, hemantjadon requested changes
There should not be changes in `clean-blog.min.css` I guess. This is the vendor file.

2016-12-27 13:06 UTC, hemantjadon commented on css/clean-blog.min.css
> + */a,body{color:#333}.navbar-custom .nav li a,.navbar-custom .navbar-brand,h1,h2,h3,h4,h5,h6{font-weight:600}.caption,.intro-header .page-heading,.intro-header .site-heading,footer .copyright{text-al
Why changes in the this file?

2016-12-27 13:16 UTC, closed without merging

2016-12-27 13:30 UTC, hemantjadon commented
@hemanthsavasere Why you close your PR's always??

2016-12-31 02:43 UTC, hemanthsavasere commented
Hi @hemantjadon 
Sorry, I didin't mean to offend anyone.
The problem here is,
the custom.css file's styles are applying to some, but I cannot override other links whose properties already has been defined in css/clean-blog.min.css for that particular elements in the paragraph.
I cannot override these.
Example: In Line 5 of the clean-blog.min.css
p a{text-decoration:underline}a:focus,a:hover{color:#e12b00}
is already specified for paragraph elements and I cannot override with in default way I need to use a class or an ID or override it in other way.
Thanks