Fixed #64 added privacy_policy.html in repo and linked it
fossasia/pslab.fossasia.org pull request #65
Opened 2017-08-19 17:41 UTC by viveksb007

Added privacy_policy.html and linked it in footer of site.

![screenshot from 2017-08-19 22-58-13](https://user-images.githubusercontent.com/12713808/29488989-9d32370c-8533-11e7-8dae-95ee70cf8e4f.png)

2017-08-20 10:24 UTC, akarshan96 approved these changes

2017-08-20 10:45 UTC, CloudyPadmal commented on index.html
> +			<i class="fa fa-info-circle" aria-hidden="true"></i> PSLab | <a href="http://fossasia.org">FOSSASIA</a> <a href="privacy_policy.html">| Privacy</a>
Hi @viveksb007 ! What if we exclude the bar line from link and start the anchor tag after it?

2017-08-20 11:14 UTC, viveksb007 commented on index.html
> +			<i class="fa fa-info-circle" aria-hidden="true"></i> PSLab | <a href="http://fossasia.org">FOSSASIA</a> <a href="privacy_policy.html">| Privacy</a>
yeah the bar line is also anchored to link. I will push a commit to fix it.

2017-08-20 12:29 UTC, CloudyPadmal approved these changes

2017-08-21 06:59 UTC, mariobehling commented
@CloudyPadmal @akarshan96 Are you actually testing the site? Top links are not working!

2017-08-21 07:00 UTC, mariobehling requested changes
* Top links don't work
![screenshot from 2017-08-21 08-58-52](https://user-images.githubusercontent.com/1583873/29507113-038bfc56-864f-11e7-8ff3-a115f8b47258.png)

* On top of privacy page, take out "Open Source Pocket Science Lab from FOSSASIA 
PSLAB HARDWARE REPO PSLAB FIRMWARE REPO PSLAB ANDROID REPO" and reduce height of area
* On bottom take out "Contact Us If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us. dev@fossasia.com"

2017-08-21 07:31 UTC, viveksb007 commented
@mariobehling I updated the PR description with test-page link yesterday. They approved based on screen cast I guess.
About top links, top bar was made taking main page into consideration where **Getting Started** and **Developers And Mentors** section is.
In privacy policy page there is no such section that why links aren't working.
So I think
- We should remove **Getting Started** and **Developer And Mentor**  from top bar when privacy policy is shown.
- Rest the changes you mentioned

Any more changes or suggestions?

2017-08-21 08:11 UTC, viveksb007 commented
@mariobehling made the requested changes.

2017-08-21 09:22 UTC, mariobehling commented
> We should remove Getting Started and Developer And Mentor from top bar when privacy policy is shown.

Please speed this up and avoid additional changes. Just stay with the issue description. Top bar should stay the same as on main page.

2017-08-21 09:33 UTC, viveksb007 commented
@mariobehling all the links in top bar works now. No additional change in top bar.

2017-08-21 10:25 UTC, CloudyPadmal commented on privacy_policy.html
> +                    <a href="#features" title="Features">Features</a>
Hi @viveksb007 ! I guess this link needs to be changed right? As this points to a div. Does it work?

2017-08-21 10:29 UTC, viveksb007 commented on privacy_policy.html
> +                    <a href="#features" title="Features">Features</a>
Sorry my bad. Missed one, it should be `index.html#features`

2017-08-21 15:00 UTC, mariobehling commented
Please rename "privacy_policy.html" to "privacy.html"

2017-08-21 18:55 UTC, viveksb007 commented
@mariobehling renamed **privacy_policy.html** to **privacy.html**

2017-08-22 12:46 UTC, mariobehling approved these changes

2017-08-22 12:47 UTC, mariobehling commented
Thanks!

2017-08-22 12:47 UTC, merged