Added Darwin Gosal in the mentors #63
fossasia/pslab.fossasia.org pull request #72
Opened 2017-10-19 11:55 UTC by lapmid

2017-10-19 13:22 UTC, viveksb007 commented
@lapmid Please squash your commits and try to finalise work before pushing. That's way more commits for this simple issue.

2017-10-19 13:33 UTC, lapmid commented
Sorry actually i was mistaken and pushed then i tried to make that correct
so thats why too much pushes

On 19-Oct-2017 6:52 PM, "Vivek Singh" <notifications@github.com> wrote:

> @lapmid <https://github.com/lapmid> Please squash your commits and try to
> finalise work before pushing. That's way more commits for this simple issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/pslab.fossasia.org/pull/72#issuecomment-337906181>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AemYmFvawAZdSjgmeLpqcQOOrPiFhujrks5st00ygaJpZM4P_HN2>
> .
>

2017-10-19 13:36 UTC, lapmid commented
And again sorry actually little bit beginer on github so i made commits everytime i made a correction

2017-10-23 07:53 UTC, CloudyPadmal commented on index.html
> +                            <h3 id="hongphuc">Darvin Gosal</h3>
Change the id to "darvin"

2017-10-23 07:53 UTC, CloudyPadmal commented on index.html
> +
Remove the extra spaces and align the <p> tags

2017-10-23 07:54 UTC, CloudyPadmal commented on index.html
> +                            <p>Darwin Gosal is the Founder of <a href="http://http://www.cryowerx.com">CryoWerx</a>,an F&B retail platform using cloud-connected smart-kiosk. As a member of <a href="h
There are some extra spaces in this section and some misses spaces after commas

2017-10-23 07:55 UTC, CloudyPadmal commented on index.html
> +                            <p>Darwin Gosal is the Founder of <a href="http://http://www.cryowerx.com">CryoWerx</a>,an F&B retail platform using cloud-connected smart-kiosk. As a member of <a href="h
Fix the link `<a href="http://http://www.cryowerx.com">`

2017-10-23 07:55 UTC, CloudyPadmal commented on index.html
> +                            <h3 id="hongphuc">Mitch Altman</h3>
Change the id to altman

2017-10-23 07:55 UTC, CloudyPadmal commented on index.html
> +
Extra space can be removed and tags can be aligned!

2017-10-23 07:56 UTC, CloudyPadmal requested changes
Hi! I've requested some changes! :)

2017-10-23 08:01 UTC, lapmid commented
Okay i wilk do it

On 23-Oct-2017 1:26 PM, "Padmal" <notifications@github.com> wrote:

> *@CloudyPadmal* requested changes on this pull request.
>
> Hi! I've requested some changes! :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/pslab.fossasia.org/pull/72#pullrequestreview-71093203>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AemYmNUROzVOq7A4voJig6xFSjW6NXYBks5svEadgaJpZM4P_HN2>
> .
>

2017-10-23 09:36 UTC, lapmid commented
@CloudyPadmal I have done changes there was also some prior wrong id's i
have also fixed that please review

On 23-Oct-2017 1:31 PM, "anurag pandey" <lapmid258@gmail.com> wrote:

> Okay i wilk do it
>
> On 23-Oct-2017 1:26 PM, "Padmal" <notifications@github.com> wrote:
>
>> *@CloudyPadmal* requested changes on this pull request.
>>
>> Hi! I've requested some changes! :)
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/fossasia/pslab.fossasia.org/pull/72#pullrequestreview-71093203>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AemYmNUROzVOq7A4voJig6xFSjW6NXYBks5svEadgaJpZM4P_HN2>
>> .
>>
>

2017-10-23 11:36 UTC, CloudyPadmal commented
Hi @lapmid ! Looks nice now! There is merge conflicts in the index.html and be really careful when resolving them. Conflict is due to new addition of developers.

2017-10-23 11:43 UTC, lapmid commented
Please help how to resolve them

On 23-Oct-2017 5:06 PM, "Padmal" <notifications@github.com> wrote:

> Hi @lapmid <https://github.com/lapmid> ! Looks nice now! There is merge
> conflicts in the index.html and be really careful when resolving them.
> Conflict is due to new addition of developers.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/pslab.fossasia.org/pull/72#issuecomment-338631075>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AemYmMc_aj20NOvtyPk48VWNGQqBJmGhks5svHpIgaJpZM4P_HN2>
> .
>

2017-10-23 13:26 UTC, lapmid commented
@CloudyPadmal  i have resolved conflicts kindly review

2017-10-24 17:41 UTC, lapmid commented
@CloudyPadmal  kindly review now i have removed conflicts second time now

2017-10-28 21:47 UTC, mariobehling commented
Darwin is a contributing mentor in FOSSASIA, but not a core mentor of the project. Therefore he should not be added to the project site.

2017-10-28 21:47 UTC, closed without merging

2017-10-29 03:12 UTC, lapmid commented
@mariobehling but i had also added mitch altman  and darwin gosal was written in the issue so i had added him