Fixes #93 : Converted insecure links in the codebase
fossasia/pslab.fossasia.org pull request #94
Opened 2018-05-12 16:53 UTC by abhi40308

Converted a media set link to secure link by converting http to https.

2018-05-13 03:08 UTC, CloudyPadmal approved these changes

2018-06-04 05:56 UTC, CloudyPadmal requested changes
@abhi40308 both your commits came in to this PR

2018-06-04 06:06 UTC, abhi40308 commented
@CloudyPadmal will change it 👍, i'll send from a different branch after rebasing.

2018-06-04 06:53 UTC, CloudyPadmal commented
Great :+1:

2018-06-07 09:38 UTC, closed without merging